# Generated by Django 4.1.5 on 2023-01-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_description',
            field=models.TextField(blank=True, db_column='gr_descr', null=True),
        ),
    ]
