# Generated by Django 4.1.5 on 2023-01-19 10:04

from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_start',
            field=models.DateField(validators=[groups.validators.validate_start_date]),
        ),
    ]
